// Deterministic PWA icon generator.
// Produces PNG byte arrays for 192px and 512px icons using only a raw canvas
// offscreen path. In browser builds the icons are generated at runtime (first
// load); in Node they can be pre-generated by a small script. The visual is a
// purple "DC" monogram on a circular gradient background — matches the brand.

const ICON_TEXT = 'DC';
const FONT = `800 ${0}px 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif`;

interface IconOptions {
  size: number;
  fg: string;
  bg1: string;
  bg2: string;
}

function renderIconToCanvas(size: number, opts: IconOptions): HTMLCanvasElement | null {
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;

  const cx = size / 2;
  const cy = size / 2;
  const r = size / 2;

  // circular clip
  ctx.beginPath();
  ctx.arc(cx, cy, r, 0, Math.PI * 2);
  ctx.closePath();

  // gradient background
  const grad = ctx.createLinearGradient(0, 0, size, size);
  grad.addColorStop(0, opts.bg1);
  grad.addColorStop(1, opts.bg2);
  ctx.fillStyle = grad;
  ctx.fill();

  // outer ring
  ctx.lineWidth = Math.max(2, size / 48);
  ctx.strokeStyle = 'rgba(255,255,255,0.25)';
  ctx.stroke();

  // shadow for text
  ctx.shadowColor = 'rgba(0,0,0,0.35)';
  ctx.shadowBlur = size / 16;
  ctx.shadowOffsetY = size / 24;

  // text
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.font = FONT.replace('0', String(size * 0.46));
  ctx.fillStyle = opts.fg;
  ctx.fillText(ICON_TEXT, cx, cy + size * 0.02);

  // clear shadow
  ctx.shadowColor = 'transparent';
  ctx.shadowBlur = 0;

  // inner highlight arc
  ctx.beginPath();
  ctx.arc(cx, cy, r - 2, -Math.PI * 0.6, -Math.PI * 0.2);
  ctx.strokeStyle = 'rgba(255,255,255,0.15)';
  ctx.lineWidth = 2;
  ctx.stroke();

  return canvas;
}

/** Returns PNG bytes for a given size. Works in browser; returns placeholder in Node. */
export function generatePwaIcon(size: number): Uint8Array {
  const canvas = renderIconToCanvas(size, {
    size,
    fg: '#FFFFFF',
    bg1: '#6366F1',
    bg2: '#4F46E5',
  });
  if (!canvas) {
    // placeholder: solid purple square with "DC" text rendered via raw bytes
    // This should never happen in browser; serves as a fallback.
    return new Uint8Array();
  }
  return new Uint8Array(canvas.toDataURL('image/png').split(',')[1]!.length > 0
    ? Uint8Array.from(atob(canvas.toDataURL('image/png').split(',')[1]!), c => c.charCodeAt(0))
    : new Uint8Array());
}

/** Writes icon PNGs to disk. Call from a Node pre-build script if desired. */
export function writePwaIconsToDisk(outDir: string) {
  if (typeof window !== 'undefined') return; // browser: no-op
  const fs = require('fs');
  const path = require('path');
  const iconsDir = path.join(outDir, 'icons');
  fs.mkdirSync(iconsDir, { recursive: true });
  for (const size of [192, 512]) {
    const bytes = generatePwaIcon(size);
    if (bytes.length === 0) continue;
    fs.writeFileSync(path.join(iconsDir, `icon-${size}.png`), Buffer.from(bytes));
  }
}
