// Minimal PWA service worker registration helper.
// In production the actual service worker sw.js is generated by vite-plugin-pwa
// and served from the dist root. This file just registers it and handles updates.
// It does NOT inline a service worker — that would bypass the plugin's asset
// hashing and break updates.

declare global {
  interface Navigator {
    // @ts-ignore
    serviceWorker: ServiceWorkerContainer;
  }
}

export function registerPwaServiceWorker() {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return;

  // The plugin emits /sw.js at the dist root. In development we don't register
  // so HMR keeps working; only register in production.
  if (import.meta.env.PROD) {
    navigator.serviceWorker
      .register('/sw.js')
      .then((reg) => {
        // Check for updates on a fresh page load
        if (reg.waiting) {
          notifyUser(reg.waiting);
        } else {
          reg.addEventListener('updatefound', () => {
            const newWorker = reg.installing;
            if (!newWorker) return;
            newWorker.addEventListener('statechange', () => {
              if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                notifyUser(newWorker);
              }
            });
          });
        }
      })
      .catch((err) => {
        console.warn('PWA service worker registration failed:', err);
      });
  }
}

function notifyUser(worker: ServiceWorker) {
  // Simple toast-style prompt to refresh for the latest version.
  // The actual toast UI is handled by react-hot-toast which is already a dep.
  const event = new CustomEvent('pwa-update-available', { detail: worker });
  window.dispatchEvent(event);
}
